stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Hello, World! Building the project..."

test:
  stage: test
  script:
    - echo "Hello, World! Testing the project..."

deploy:
  stage: deploy
  script:
    - echo "Hello, World! Deploying the project...."
